name: ProfileServicePipeline

on:
  pull_request:
    branches: [ "dev" ]

jobs:
  compile:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B clean compile package -Dmaven.test.skip=true


  test:

    runs-on: ubuntu-latest
    needs: [compile]

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run Tests
        run: mvn test --batch-mode
      - name: Publish Test Report
        if: ${{ always() }}
        uses: scacap/action-surefire-report@v1